export const ships = [
  {
    id: "ship-1",
    name: "VESSEL 1001",
    vesselType: "TANKER",
    lat: 26.62,
    lon: 56.95,
    speed: 14,
    heading: 270,
    status: "IN TRANSIT",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
  {
    id: "ship-2",
    name: "VESSEL 1002",
    vesselType: "CARGO",
    lat: 26.60,
    lon: 56.78,
    speed: 11,
    heading: 270,
    status: "IN TRANSIT",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
  {
    id: "ship-3",
    name: "VESSEL 1003",
    vesselType: "UNKNOWN",
    lat: 26.57,
    lon: 56.55,
    speed: 9,
    heading: 270,
    status: "MONITORING",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
  {
    id: "ship-4",
    name: "VESSEL 1004",
    vesselType: "TANKER",
    lat: 26.53,
    lon: 56.30,
    speed: 13,
    heading: 270,
    status: "IN TRANSIT",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
  {
    id: "ship-5",
    name: "VESSEL 1005",
    vesselType: "CARGO",
    lat: 26.50,
    lon: 56.05,
    speed: 10,
    heading: 270,
    status: "EXITING STRAIT",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },

  {
    id: "ship-6",
    name: "VESSEL 1006",
    vesselType: "TANKER",
    lat: 26.18,
    lon: 55.80,
    speed: 12,
    heading: 90,
    status: "IN TRANSIT",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
  {
    id: "ship-7",
    name: "VESSEL 1007",
    vesselType: "CARGO",
    lat: 26.20,
    lon: 56.00,
    speed: 15,
    heading: 90,
    status: "IN TRANSIT",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
  {
    id: "ship-8",
    name: "VESSEL 1008",
    vesselType: "UNKNOWN",
    lat: 26.23,
    lon: 56.22,
    speed: 8,
    heading: 90,
    status: "MONITORING",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
  {
    id: "ship-9",
    name: "VESSEL 1009",
    vesselType: "TANKER",
    lat: 26.26,
    lon: 56.45,
    speed: 11,
    heading: 90,
    status: "IN TRANSIT",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
  {
    id: "ship-10",
    name: "VESSEL 1010",
    vesselType: "CARGO",
    lat: 26.29,
    lon: 56.70,
    speed: 14,
    heading: 90,
    status: "EXITING STRAIT",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },

  {
    id: "ship-11",
    name: "VESSEL 1011",
    vesselType: "TANKER",
    lat: 26.40,
    lon: 56.12,
    speed: 0,
    heading: 0,
    status: "STATIONARY",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
  {
    id: "ship-12",
    name: "VESSEL 1012",
    vesselType: "UNKNOWN",
    lat: 26.34,
    lon: 56.88,
    speed: 0,
    heading: 0,
    status: "STATIONARY",
    signalType: "AIS",
    timestamp: new Date().toISOString(),
    mediaUrl: "",
  },
];